syntax = "proto3";

package chat;

service ChatService {
  rpc SendMessage (SendMessageRequest) returns (SendMessageReply);
  rpc StreamMessages (StreamRequest) returns (stream ChatMessage);
  rpc ChatStream (stream ChatMessage) returns (stream ChatMessage);
}

message SendMessageRequest {
  string room_id = 1;
  string user_id = 2;
  string text = 3;
}

message SendMessageReply {
  string message_id = 1;
  int64 server_ts = 2;
  string status = 3;
}

message StreamRequest {
  string room_id = 1;
}

message ChatMessage {
  string room_id = 1;
  string user_id = 2;
  string text = 3;
  int64 ts = 4;
}
